version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: binky-backend
    ports:
      - "8000:8000"
    volumes:
      - ./utils:/app/utils
      - ./src:/app/src
      - ./config.py:/app/config.py
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
    networks:
      - binky-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: binky-frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - binky-network

networks:
  binky-network:
    driver: bridge