# docker-compose.yml
version: '3.8'

services:
  # Backend FastAPI service
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data  # Mount data folder untuk documents
      - ./models:/app/models  # Mount models folder
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Streamlit service (optional)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000
    restart: unless-stopped

  # Vector database (optional - jika pakai external DB)
  # vectordb:
  #   image: qdrant/qdrant
  #   ports:
  #     - "6333:6333"
  #   volumes:
  #     - ./qdrant_data:/qdrant/storage